### PR TITLE
Add test for SimpleSmartAnswer to Answer conversion

### PR DESCRIPTION
**Pull request by binaryberry**
The functionality is already there, but there was no test coverage for it. 

The ability to change a Simple Smart Answer to an Answer has been requested by the content team, and will require code changes in the publisher app.

[Trello](https://trello.com/c/siIF3DDX/83-self-serve-changing-the-format-of-a-simple-smart-answer-to-a-quick-answer-small)

### CODE REVIEW

**Comment by jamiecobbett** [comment]
I don't think that a test is needed for this because it is generic behaviour - if it had any custom behaviour, then there would be a stronger case for a test.

**Comment by boffbowsh** [comment]
I dunno, I think this is valid as it ensures that this use case is compatible with the logic in the gem. It also asserts that the fields are being mapped correctly. Plus, more tests never<sup>*</sup> hurt.

**Comment by fofr** [comment]
I agree with @boffbowsh. I like that the test indicates there is no custom behaviour when converting a SimpleSmartAnswer.

**Comment by jamiecobbett** [comment]
I think I've figured out what was bothering me: the implementation seems unnecessarily complicated and specific. I've taken a stab at fixing it here: https://github.com/alphagov/govuk_content_models/pull/330

With my suggested change, perhaps we can more confidently provide an interface that lets users convert between any Edition type? If so, is this test still as valuable?

**Pull request merged**
