### PR TITLE
Revert "Remove specialist documents"

### PR DESCRIPTION
**Pull request by tommyp**
Reverts alphagov/govuk_content_models#318

### CODE REVIEW

**Comment by tommyp** [comment]
Reverting because we still need Manuals.

**Comment by bradleywright** [comment]
If you only need manuals, could you clean this up so it only keeps those? Seems like we could remove all the `*aib-reports` etc. and the `RenderedSpecialistDocument` models at least.

**Comment by boffbowsh** [comment]
For if/when this eventually gets unreverted, please take this comment into account https://github.com/alphagov/govuk_content_models/pull/318#issuecomment-127281561

**Comment by benilovj** [comment]
I've rebased this against master

**Comment by benilovj** [comment]
Merging this revert because it's [breaking Panopticon](https://github.com/alphagov/govuk_content_models/pull/318#issuecomment-127281561).

**Pull request merged**
